#!/bin/sh -ex

MINKVER="2.6.24"
PREREQ=""
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

# Output pre-requisites
prereqs() {
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/swapon /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/resize2fs /sbin
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /sbin/dumpe2fs /sbin
copy_exec /lib/$DEB_HOST_MULTIARCH/libz.so.1
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libcrypto.so
if [ -e /usr/lib/$DEB_HOST_MULTIARCH/libdl.so.2 ]; then
	# Bookworm+
	copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libdl.so.2
else
	copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libdl.so
fi

# Droidian: copy Droidian stuff compiled against a more recent distribution
if [ -e /orig ]; then
	copy_file_downgrade() {
		local type src target link_target

		type="${1}"
		src="${2}"
		target="${3:-$2}"

		copy_file "${type}" "${src}" "${target}"
		if [ -n "${DROIDIAN_BOOTSTRAP_ROOT_PATH}" ]; then
			/usr/sbin/chroot /orig env PATH="/usr/bin:/usr/sbin:/sbin:/bin" /usr/bin/glibc-downgrade 2.24 "${DROIDIAN_BOOTSTRAP_ROOT_PATH}/${DESTDIR}/${src}" || exit 1
		else
			echo "DROIDIAN_BOOTSTRAP_ROOT_PATH is not set. Downgrading will not work."
		fi
	}

	# Re-define copy_exec on stretch, make it skip 'not found' on symbols
	copy_exec() {
		local src target x nonoptlib ret

		src="${1}"
		target="${2:-$1}"

		copy_file_downgrade binary "${src}" "${target}" || return $(($? - 1))

		# Copy the dependant libraries
		for x in $(ldd "${src}" 2>/dev/null | sed -e '
			/\//!d;
			/linux-gate/d;
			/not found/d;
			/=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
			s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do

			# Try to use non-optimised libraries where possible.
			# We assume that all HWCAP libraries will be in tls,
			# sse2, vfp or neon.
			nonoptlib=$(echo "${x}" | sed -e 's#/lib/\([^/]*/\)\?\(tls\|i686\|sse2\|neon\|vfp\).*/\(lib.*\)#/lib/\1\3#')
			nonoptlib=$(echo "${nonoptlib}" | sed -e 's#-linux-gnu/\(tls\|i686\|sse2\|neon\|vfp\).*/\(lib.*\)#-linux-gnu/\2#')

			if [ -e "${nonoptlib}" ]; then
				x="${nonoptlib}"
			fi

			copy_file_downgrade library "${x}" || {
				ret=$?
				[ ${ret} = 1 ] || return $((ret - 1))
			}
		done
	}

	LD_LIBRARY_PATH="/lib/${DEB_HOST_MULTIARCH}:/usr/lib/${DEB_HOST_MULTIARCH}:/orig/lib/${DEB_HOST_MULTIARCH}:/orig/usr/lib/${DEB_HOST_MULTIARCH}"
	export LD_LIBRARY_PATH

	ldd /orig/usr/bin/unl0kr
	copy_exec /orig/usr/bin/unl0kr
	cp /orig/etc/unl0kr.conf "${DESTDIR}/etc"

	copy_exec /orig/usr/sbin/droidian-encryption-helper

	echo "Merging contents of ${DESTDIR}/orig"
	cp -Rv ${DESTDIR}/orig/* "${DESTDIR}"
	rm -rf ${DESTDIR}/orig

	unset LD_LIBRARY_PATH
fi

# Droidian: copy touchscreen rules
mkdir -p "${DESTDIR}/etc/udev/rules.d"
cp /etc/udev/rules.d/90-touchscreen.rules "${DESTDIR}/etc/udev/rules.d"

# Droidian: copy /usr/share/X11/xkb
mkdir -p "${DESTDIR}/usr/share/X11/xkb"
cp -R /usr/share/X11/xkb/* "${DESTDIR}/usr/share/X11/xkb"

# Droidian: copy udev hwdb
mkdir -p "${DESTDIR}/usr/lib/udev/hwdb.d"
cp -R /usr/lib/udev/hwdb.d/* "${DESTDIR}/usr/lib/udev/hwdb.d"
