#!/bin/sh -e

MINKVER="2.6.24"
PREREQ=""
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

# Output pre-requisites
prereqs() {
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/swapon /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/resize2fs /sbin
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /bin/libinput /bin
copy_exec /sbin/dumpe2fs /sbin
copy_exec /lib/$DEB_HOST_MULTIARCH/libz.so.1
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libcrypto.so
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libdl.so.2
copy_exec /usr/bin/evtest /bin

# libinput: copy quirks
mkdir -p "${DESTDIR}/usr/share/libinput"
cp /usr/share/libinput/* "${DESTDIR}/usr/share/libinput"

# libinput: copy libinput tools
mkdir -p "${DESTDIR}/usr/libexec/libinput"
cp /usr/libexec/libinput/* "${DESTDIR}/usr/libexec/libinput"

# Droidian: copy touchscreen rules
mkdir -p "${DESTDIR}/etc/udev/rules.d"
cp /etc/udev/rules.d/90-touchscreen.rules "${DESTDIR}/etc/udev/rules.d"

# Droidian: copy /usr/share/X11/xkb
mkdir -p "${DESTDIR}/usr/share/X11/xkb"
cp -R /usr/share/X11/xkb/* "${DESTDIR}/usr/share/X11/xkb"

# Droidian: copy udev hwdb
mkdir -p "${DESTDIR}/usr/lib/udev/hwdb.d"
cp -R /usr/lib/udev/hwdb.d/* "${DESTDIR}/usr/lib/udev/hwdb.d"
